services:
  - mysql
  - mongodb
  - redis-server
  - rabbitmq
language: python
sudo: required
cache: pip
python:
  - '2.7'
os:
  - 'linux'
script:
  - python fastweb/test/service_server.py
  - pytest

